### ISSUE TITLE
Support multiple aliases at the same time?

### ISSUE THREAD

**Issue by Ocramius** [Tecnativa/docker-whitelist#10]
I inherited a project that uses this container. The setup looks as follows:

```yml
  proxy_i_vimeocdn_com:
    image: tecnativa/whitelist
    environment:
      TARGET: i.vimeocdn.com
      PRE_RESOLVE: 1 # Otherwise it would resolve to localhost
    networks:
      e2e-test-suite-network:
        aliases:
          - i.vimeocdn.com

  proxy_f_vimeocdn_com:
    image: tecnativa/whitelist
    environment:
      TARGET: f.vimeocdn.com
      PRE_RESOLVE: 1 # Otherwise it would resolve to localhost
    networks:
      e2e-test-suite-network:
        aliases:
          - f.vimeocdn.com

# More here (lots more)
```

I was wondering if there's a way to have `TARGET` contain a CSV host list? :thinking:

**Comment by pedrobaeza** [comment]
Although it's an interesting feature, it's not implemented right now and you should put multiple points. Technically, I don't know right now which are the challenges to implement something like that. You can try to and contribute it in a pull request if you think it's feasible.

**Comment by Ocramius** [comment]
Yeah, was looking at the code, and it seems like `proxy.py` would need to be rewritten completely, since only one `ip` is resolved right now :thinking: 

https://github.com/Tecnativa/docker-whitelist/blob/a4e0d2839aa08476c139d5e3d772a85ae17e1058/proxy.py#L14-L21

Also, it would only work if a `Host` header is parsed, so it's no longer just a transparent proxy.

**Comment by Ocramius** [comment]
Gonna close here: I cannot currently work on this myself, as it completely redesigns everything, but I hope this is still useful to others :) 

Meanwhile, I found an approach that better fits my own use-case, by using Traefik as a load balancer pointing to an external network:

```yml
http:
  routers:
    foobar:
      entryPoints:
      - websecure
      middlewares:
      - strip
      service: myexthost
      rule: Host(`dev.mytraefikhost.de`) && Path(`/myexthost/www`)
      tls: {}

  myexthost:
    foobar:
      loadBalancer:
        servers:
        - url: https://www.myexthost.de
 
  middlewares:
    strip:
      stripPrefix:
        prefixes:
        - /myexthost/www
```

See https://community.traefik.io/t/reverse-proxy-to-external-host/3615/4

This requires putting traefik on a non-`internal` network, as well as a second `internal` network that does **not** have the `www.myexthost.de` as part of its internal DNS aliases.

That's obviously very much overkill for most folks, so this project is still very much valid in its own scope, just hoping this is useful to others.
