### ISSUE TITLE
Cannot start on a mac M1

### ISSUE THREAD

**Issue by piqoni** [Tecnativa/docker-whitelist#7]
Odoo image was built successfully but at the last step of the doodba set-up, when I perform a 'docker-compose up -d' I get the following error. Does anyone have found a workaround? 

```
Digest: sha256:e6e1d1d41fb7087250176b38c73666c1205816e8b8d2d8f8f4a69ce23f7635b3
Status: Downloaded newer image for kozea/wdb:latest
Pulling cdnjs_cloudflare_proxy (tecnativa/whitelist:)...
latest: Pulling from tecnativa/whitelist
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by joao-p-marques** [comment]
This would be a good improvement, as that is quite a common architecture (also used on Raspberry Pi 4, for example). 
However, the build currently fails if we try this, so we ended up removing for now...

**Comment by piqoni** [comment]
Thanks @joao-p-marques. Looking forward for a fix. 🙌   Meanwhile, does anyone have any suggestion for a workaround, perhaps disabling the whitelist from docker-compose? In my scenario, I simply want to make the image work locally. 🤞

**Comment by joao-p-marques** [comment]
@piqoni you could just disable every service that uses that image, and remove the dependency from the odoo container to those services. The problem is that we run odoo in a docker internal network, so you'd either have it not contacting those services that we are whitelisting, or open it to a normal docker network and potentially face some mail sending issues.

**Comment by dnplkndll** [comment]
> Odoo image was built successfully but at the last step of the doodba set-up, when I perform a 'docker-compose up -d' I get the following error. Does anyone have found a workaround?
> 
> ```
> Digest: sha256:e6e1d1d41fb7087250176b38c73666c1205816e8b8d2d8f8f4a69ce23f7635b3
> Status: Downloaded newer image for kozea/wdb:latest
> Pulling cdnjs_cloudflare_proxy (tecnativa/whitelist:)...
> latest: Pulling from tecnativa/whitelist
> ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
> ```

just add
```
    platform: "linux/amd64"
```
like:
```
  # Whitelist outgoing traffic for tests, reports, etc.
  proxy_cdnjs_cloudflare_com:
    image: ghcr.io/tecnativa/docker-whitelist:latest
    platform: "linux/amd64"
    networks:
      default:
        aliases:
          - cdnjs.cloudflare.com
      public:
    environment:
      TARGET: cdnjs.cloudflare.com
      PRE_RESOLVE: 1
```
